import { EStatus } from '@/enums/status.enum';
import { Pokemon } from '@/modules/pokemon/pokemon.entity';

import {
  RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR,
  RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR,
  RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR,
} from '@/modules/pokemon/fixtures/response/full';

import {
  ENTITIES_MOVES_FIXTURE_BULBASAUR,
  ENTITIES_MOVES_FIXTURE_IVYSAUR,
  ENTITIES_MOVES_FIXTURE_VENUSAUR,
} from '@/modules/pokemon/move/move.fixture';
import { ENTITIES_ABILITIES_FIXTURE } from '@/modules/pokemon/ability/ability.fixture';
import { ENTITIES_TYPES_FIXTURE } from '@/modules/pokemon/type/type.fixture';

export const ENTITY_POKEMON_FIXTURE_BULBASAUR: Pokemon = {
  id: RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.id,
  url: RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.url,
  name: RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.name,
  order: RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.order,
  status: EStatus.INCOMPLETE,
  image: undefined,
  moves: [],
  types: [],
  // stats: [],
  habitat: undefined,
  is_baby: undefined,
  shape_url: undefined,
  abilities: [],
  evolutions: [],
  shape_name: undefined,
  is_mythical: undefined,
  gender_rate: undefined,
  is_legendary: undefined,
  capture_rate: undefined,
  hatch_counter: undefined,
  base_happiness: undefined,
  evolution_chain_url: undefined,
  evolves_from_species: undefined,
  has_gender_differences: undefined,
  createdAt: new Date('1990-01-01'),
  updatedAt: new Date('1990-01-01'),
  deletedAt: undefined,
};
export const ENTITY_POKEMON_FIXTURE_IVYSAUR: Pokemon = {
  id: RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.id,
  url: RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.url,
  name: RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.name,
  order: RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.order,
  status: EStatus.INCOMPLETE,
  image: undefined,
  moves: [],
  types: [],
  // stats: [],
  habitat: undefined,
  is_baby: undefined,
  shape_url: undefined,
  abilities: [],
  evolutions: [],
  shape_name: undefined,
  is_mythical: undefined,
  gender_rate: undefined,
  is_legendary: undefined,
  capture_rate: undefined,
  hatch_counter: undefined,
  base_happiness: undefined,
  evolution_chain_url: undefined,
  evolves_from_species: undefined,
  has_gender_differences: undefined,
  createdAt: new Date('1990-01-01'),
  updatedAt: new Date('1990-01-01'),
  deletedAt: undefined,
};
export const ENTITY_POKEMON_FIXTURE_VENUSAUR: Pokemon = {
  id: RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.id,
  url: RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.url,
  name: RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.name,
  order: RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.order,
  status: EStatus.INCOMPLETE,
  image: undefined,
  moves: [],
  types: [],
  // stats: [],
  habitat: undefined,
  is_baby: undefined,
  shape_url: undefined,
  abilities: [],
  evolutions: [],
  shape_name: undefined,
  is_mythical: undefined,
  gender_rate: undefined,
  is_legendary: undefined,
  capture_rate: undefined,
  hatch_counter: undefined,
  base_happiness: undefined,
  evolution_chain_url: undefined,
  evolves_from_species: undefined,
  has_gender_differences: undefined,
  createdAt: new Date('1990-01-01'),
  updatedAt: new Date('1990-01-01'),
  deletedAt: undefined,
};

export const ENTITY_POKEMON_COMPLETE_FIXTURE_BULBASAUR: Pokemon = {
  id: RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.id,
  url: RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.url,
  name: RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.name,
  image: RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.image,
  moves: ENTITIES_MOVES_FIXTURE_BULBASAUR,
  order: RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.order,
  types: ENTITIES_TYPES_FIXTURE,
  // stats: ENTITIES_STATS_FIXTURE,
  status: EStatus.COMPLETE,
  habitat: RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.habitat,
  is_baby: RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.is_baby,
  shape_url: RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.shape_url,
  abilities: ENTITIES_ABILITIES_FIXTURE,
  evolutions: [],
  shape_name: RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.shape_name,
  is_mythical: RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.is_mythical,
  gender_rate: RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.gender_rate,
  is_legendary: RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.is_legendary,
  capture_rate: RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.capture_rate,
  hatch_counter: RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.hatch_counter,
  base_happiness: RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.base_happiness,
  evolution_chain_url:
    RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.evolution_chain_url,
  evolves_from_species:
    RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.evolves_from_species,
  has_gender_differences:
    RESPONSE_POKEMON_FULL_FIXTURE_BULBASAUR.has_gender_differences,
  createdAt: new Date('1990-01-01'),
  updatedAt: new Date('1990-01-02'),
  deletedAt: undefined,
};
export const ENTITY_POKEMON_COMPLETE_FIXTURE_IVYSAUR: Pokemon = {
  id: RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.id,
  url: RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.url,
  name: RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.name,
  image: RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.image,
  moves: ENTITIES_MOVES_FIXTURE_IVYSAUR,
  order: RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.order,
  types: ENTITIES_TYPES_FIXTURE,
  // stats: ENTITIES_STATS_FIXTURE,
  status: EStatus.COMPLETE,
  habitat: RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.habitat,
  is_baby: RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.is_baby,
  shape_url: RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.shape_url,
  abilities: ENTITIES_ABILITIES_FIXTURE,
  evolutions: [],
  shape_name: RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.shape_name,
  is_mythical: RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.is_mythical,
  gender_rate: RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.gender_rate,
  is_legendary: RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.is_legendary,
  capture_rate: RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.capture_rate,
  hatch_counter: RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.hatch_counter,
  base_happiness: RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.base_happiness,
  evolution_chain_url:
    RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.evolution_chain_url,
  evolves_from_species:
    RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.evolves_from_species,
  has_gender_differences:
    RESPONSE_POKEMON_FULL_FIXTURE_IVYSAUR.has_gender_differences,
  createdAt: new Date('1990-01-01'),
  updatedAt: new Date('1990-01-02'),
  deletedAt: undefined,
};
export const ENTITY_POKEMON_COMPLETE_FIXTURE_VENUSAUR: Pokemon = {
  id: RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.id,
  url: RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.url,
  name: RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.name,
  image: RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.image,
  moves: ENTITIES_MOVES_FIXTURE_VENUSAUR,
  order: RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.order,
  types: ENTITIES_TYPES_FIXTURE,
  // stats: ENTITIES_STATS_FIXTURE,
  status: EStatus.COMPLETE,
  habitat: RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.habitat,
  is_baby: RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.is_baby,
  shape_url: RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.shape_url,
  abilities: ENTITIES_ABILITIES_FIXTURE,
  evolutions: [],
  shape_name: RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.shape_name,
  is_mythical: RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.is_mythical,
  gender_rate: RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.gender_rate,
  is_legendary: RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.is_legendary,
  capture_rate: RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.capture_rate,
  hatch_counter: RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.hatch_counter,
  base_happiness: RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.base_happiness,
  evolution_chain_url:
    RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.evolution_chain_url,
  evolves_from_species:
    RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.evolves_from_species,
  has_gender_differences:
    RESPONSE_POKEMON_FULL_FIXTURE_VENUSAUR.has_gender_differences,
  createdAt: new Date('1990-01-01'),
  updatedAt: new Date('1990-01-02'),
  deletedAt: undefined,
};
